In [1]:
import pyspark 
import uuid
import pandas as pd

In [3]:
sc = pyspark.SparkContext('local','job_.{0}'.format(uuid.uuid4()))

In [4]:
data = pd.read_csv("movies.csv")

In [5]:
rdd_data = sc.parallelize([ list(r)[2:-1] for r in data.itertuples()])

In [6]:
rdd_data.getNumPartitions()

1

In [9]:
rdd_data.repartition(10).getNumPartitions()

10

In [10]:
rdd_data.coalesce(2).getNumPartitions()

1

In [11]:
rdd_data.take(5)

[['$',
  1971,
  121,
  nan,
  6.4,
  348,
  4.5,
  4.5,
  4.5,
  4.5,
  14.5,
  24.5,
  24.5,
  14.5,
  4.5,
  4.5,
  nan,
  0,
  0,
  1,
  1,
  0,
  0],
 ['$1000 a Touchdown',
  1939,
  71,
  nan,
  6.0,
  20,
  0.0,
  14.5,
  4.5,
  24.5,
  14.5,
  14.5,
  14.5,
  4.5,
  4.5,
  14.5,
  nan,
  0,
  0,
  1,
  0,
  0,
  0],
 ['$21 a Day Once a Month',
  1941,
  7,
  nan,
  8.2,
  5,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  24.5,
  0.0,
  44.5,
  24.5,
  24.5,
  nan,
  0,
  1,
  0,
  0,
  0,
  0],
 ['$40,000',
  1996,
  70,
  nan,
  8.2,
  6,
  14.5,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  34.5,
  45.5,
  nan,
  0,
  0,
  1,
  0,
  0,
  0],
 ['$50,000 Climax Show, The',
  1975,
  71,
  nan,
  3.4,
  17,
  24.5,
  4.5,
  0.0,
  14.5,
  14.5,
  4.5,
  0.0,
  0.0,
  0.0,
  24.5,
  nan,
  0,
  0,
  0,
  0,
  0,
  0]]

In [12]:
rdd_data.map( lambda x: json.JSONEncoder().encode({ str(k):str(v) for
(k,v) in zip(data.columns[2:-1],x)})).\
saveAsTextFile('movies.json')

In [18]:
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)
df = sqlContext.read.json("movies.json")

In [19]:
df.cache()

DataFrame[Action: string, Animation: string, Comedy: string, Documentary: string, Drama: string, Romance: string, budget: string, length: string, mpaa: string, r1: string, r10: string, r2: string, r3: string, r4: string, r5: string, r6: string, r7: string, r8: string, r9: string, rating: string, votes: string, year: string]

In [20]:
df.registerTempTable('movies')

In [21]:
sqlContext.sql(' select * from movies limit 5 ').show()

+------+---------+------+-----------+-----+-------+------+------+----+---+----+----+----+---+----+----+----+----+----+------+-----+--------------------+
|Action|Animation|Comedy|Documentary|Drama|Romance|budget|length|mpaa| r1| r10|  r2|  r3| r4|  r5|  r6|  r7|  r8|  r9|rating|votes|                year|
+------+---------+------+-----------+-----+-------+------+------+----+---+----+----+----+---+----+----+----+----+----+------+-----+--------------------+
|   nan|        0|     0|          1|    1|      0|   121|  1971| 4.5|348| 4.5| 4.5| 4.5|4.5| 4.5|14.5|24.5|24.5|14.5|   nan|  6.4|                   $|
|   nan|        0|     0|          0|    1|      0|    71|  1939|14.5| 20| 4.5| 0.0|14.5|4.5|24.5|14.5|14.5|14.5| 4.5|   nan|  6.0|   $1000 a Touchdown|
|   nan|        0|     1|          0|    0|      0|     7|  1941|24.5|  5|24.5| 0.0| 0.0|0.0| 0.0| 0.0|24.5| 0.0|44.5|   nan|  8.2|$21 a Day Once a ...|
|   nan|        0|     0|          0|    1|      0|    70|  1996|45.5|  6|34.5|14.5| 0.0|0.0| 0.0| 0.0| 0.0| 0.0| 0.0|   nan|  8.2|             $40,000|
|   nan|        0|     0|          0|    0|      0|    71|  1975|24.5| 17| 0.0|24.5| 4.5|0.0|14.5|14.5| 4.5| 0.0| 0.0|   nan|  3.4|$50,000 Climax Sh...|
+------+---------+------+-----------+-----+-------+------+------+----+---+----+----+----+---+----+----+----+----+----+------+-----+--------------------+

In [22]:
df.groupby('year').count().collect()

[Row(year='10.7', count=1),
 Row(year='20. Juli, Der', count=1),
 Row(year='30 Foot Bride of Candy Rock, The', count=1),
 Row(year='40 Guns to Apache Pass', count=1),
 Row(year='Absolutely Positive', count=1),
 Row(year='Achtung! Banditi!', count=1),
 Row(year='Adventure of the Wrong Santa Claus, The', count=1),
 Row(year='Adventures of Popeye', count=1),
 Row(year="Ain't She Sweet", count=1),
 Row(year='Along the Navajo Trail', count=1),
 Row(year='Amants de Teruel, Les', count=1),
 Row(year='Amateur', count=1),
 Row(year='Anna Lucasta', count=2),
 Row(year='Anniversary, The', count=2),
 Row(year='Another Face', count=1),
 Row(year='Anything Once', count=1),
 Row(year='Arche Noah Prinzip, Das', count=1),
 Row(year='Are You Popular?', count=1),
 Row(year='As Young as We Are', count=1),
 Row(year='Asphalto', count=1),
 Row(year='Aviator, The', count=2),
 Row(year='Band Plays On, The', count=1),
 Row(year='Bashtata na yaytzeto', count=1),
 Row(year='Bedroom Window, The', count=1),
 Row(year='Bells, The', count=1),
 Row(year='Betty Boop for President', count=1),
 Row(year='Big Shave, The', count=1),
 Row(year='Black Wax', count=1),
 Row(year='Blood of Jesus, The', count=1),
 Row(year='Boom boom', count=1),
 Row(year='Booye kafoor, atre yas', count=1),
 Row(year='Boulder Dam', count=1),
 Row(year='Bourne Identity Crisis, The', count=1),
 Row(year='Breezy', count=1),
 Row(year='Brothers in Law', count=1),
 Row(year='Brunet wieczorowa pora', count=1),
 Row(year="Bulldog Drummond's Secret Police", count=1),
 Row(year='Bum Bandit, The', count=1),
 Row(year='Buster Keaton Rides Again', count=1),
 Row(year='Cachito, El', count=1),
 Row(year='Cage II', count=1),
 Row(year='Camille 2000', count=1),
 Row(year='Cariocas, As', count=1),
 Row(year="Cavalieri che fecero l'impresa, I", count=1),
 Row(year='Cent briques et des tuiles', count=1),
 Row(year='Cercle des passions, Le', count=1),
 Row(year='Ceremonia sangrienta', count=1),
 Row(year='Chandni', count=1),
 Row(year='Chikamatsu monogatari', count=1),
 Row(year='Chorrito de sangre, Un', count=1),
 Row(year='Cicala, La', count=1),
 Row(year='Corpse Eaters', count=1),
 Row(year='County Hospital', count=1),
 Row(year='Coup de lune', count=1),
 Row(year='Crabe-tambour, Le', count=1),
 Row(year='Crisis', count=1),
 Row(year='Da grande', count=1),
 Row(year='Danjeogbiyeonsu', count=1),
 Row(year='Deadly Is the Female', count=1),
 Row(year='Deep Red', count=1),
 Row(year='Deep Rising', count=1),
 Row(year='Deuda', count=1),
 Row(year='Diana & Me', count=1),
 Row(year="Diggin' Up Business", count=1),
 Row(year='Disraeli', count=1),
 Row(year='Do It', count=1),
 Row(year='Do svidaniya, malchiki!', count=1),
 Row(year='Doctor Faustus', count=1),
 Row(year='Dodgeball', count=2),
 Row(year='Dogville', count=1),
 Row(year='Doughgirls, The', count=1),
 Row(year='Drums of Jeopardy, The', count=1),
 Row(year='Easter', count=1),
 Row(year='Ebba the Movie', count=1),
 Row(year='Echte Kerle', count=1),
 Row(year='Edges of the Lord', count=1),
 Row(year="Eli's Lesson", count=1),
 Row(year='Engel & Joe', count=1),
 Row(year='Errance', count=1),
 Row(year='Escape from the Planet of the Apes', count=1),
 Row(year='Eye of the Wolf', count=1),
 Row(year='F.T.W.', count=1),
 Row(year='Falcon and the Snowman, The', count=1),
 Row(year='Farm Frolics', count=1),
 Row(year='Fast Getaway II', count=1),
 Row(year='Father Takes a Wife', count=1),
 Row(year='Femmes, Les', count=1),
 Row(year='Flatworld', count=1),
 Row(year='Flesh and Bone', count=1),
 Row(year='Fleshburn', count=1),
 Row(year='Fong Sai-Yuk', count=1),
 Row(year='Forty Pink Winks', count=1),
 Row(year="Frank's Cock", count=1),
 Row(year='Freaked', count=1),
 Row(year='Fright Night Part II', count=1),
 Row(year='Frogmen Operation Stormbringer', count=1),
 Row(year='Frontier Flirtation; or, How the Tenderfoot Won Out, A', count=1),
 Row(year='Fubar', count=1),
 Row(year='Fuon', count=1),
 Row(year='Futari', count=1),
 Row(year='George Raft Story, The', count=1),
 Row(year='Giorgino', count=1),
 Row(year='Goat, The', count=1),
 Row(year='Gui da gui', count=1),
 Row(year="Guv'nor, The", count=1),
 Row(year='H Story', count=1),
 Row(year='Hakkyousuru kuchibiru', count=1),
 Row(year='Hakuoki', count=1),
 Row(year='Happy Ending, The', count=1),
 Row(year='Haruka naru yama no yobigoe', count=1),
 Row(year='Heart of America', count=1),
 Row(year='Heaven', count=3),
 Row(year="Hell's Five Hours", count=1),
 Row(year='Henry X', count=1),
 Row(year='History Is Made at Night', count=2),
 Row(year='Hong Kong 97', count=1),
 Row(year='How to Deal', count=1),
 Row(year='How to Start the Day', count=1),
 Row(year='I Am a Camera', count=1),
 Row(year="I'm From Hollywood", count=1),
 Row(year='Icarus Descending', count=1),
 Row(year='Im Stahlnetz des Dr. Mabuse', count=1),
 Row(year='Inazuma', count=1),
 Row(year='Ingmar Bergmanin maailma', count=1),
 Row(year="Isn't She Great", count=1),
 Row(year='Johnny Angel', count=1),
 Row(year='Jorge, um Brasileiro', count=1),
 Row(year='Jung-Gwok chiu-yan', count=1),
 Row(year='K', count=2),
 Row(year='Karaoke Fever', count=1),
 Row(year='Keetje Tippel', count=1),
 Row(year='Kin', count=1),
 Row(year='Komm, liebe Maid und mache', count=1),
 Row(year='Kozure satsujin ken', count=1),
 Row(year='L.A. D.J.', count=1),
 Row(year='Lady of Chance, A', count=1),
 Row(year='Larceny', count=1),
 Row(year='Last Grenade, The', count=1),
 Row(year='Last Seduction II, The', count=1),
 Row(year='Late Great Planet Earth, The', count=1),
 Row(year='Laughing Anne', count=1),
 Row(year='Leaving Drew', count=1),
 Row(year="Liebe '47", count=1),
 Row(year='Living in Oblivion', count=1),
 Row(year='Liza kai i alli, I', count=1),
 Row(year='Lost Planet Airmen', count=1),
 Row(year='Love-Hotel in Tirol, Das', count=1),
 Row(year='Lovely Rita', count=1),
 Row(year='Lune froide', count=1),
 Row(year='Magnifique, Le', count=1),
 Row(year='Mayis sikintisi', count=1),
 Row(year='Maze', count=1),
 Row(year='Mender of Nets, The', count=1),
 Row(year='Mi Casa, Su Casa', count=1),
 Row(year='Miracle Mile', count=1),
 Row(year='Morning, Noon and Night', count=1),
 Row(year='Mr. Perrin and Mr. Traill', count=1),
 Row(year="Mrs Caldicot's Cabbage War", count=1),
 Row(year='My Dog Shep', count=1),
 Row(year='My Flesh and Blood', count=1),
 Row(year='My Six Loves', count=1),
 Row(year='My Tango with Porn', count=1),
 Row(year='Myster General, The', count=1),
 Row(year='Naked Camera, The', count=1),
 Row(year='Nargess', count=1),
 Row(year='Nell', count=1),
 Row(year='Night Eyes', count=1),
 Row(year='Nightmares', count=2),
 Row(year='Nishi Ginza ekimae', count=1),
 Row(year='Noose, The', count=1),
 Row(year='Nur aus Liebe', count=1),
 Row(year='Occhi freddi della paura, Gli', count=1),
 Row(year='Oi ching baak min baau', count=1),
 Row(year="One Man's Way", count=1),
 Row(year='Pagan Island', count=1),
 Row(year='Passage to Ottawa, A', count=1),
 Row(year='Permission to Kill', count=1),
 Row(year='Pfingstausflug, Der', count=1),
 Row(year='Phantom Horsemen, The', count=1),
 Row(year='Pisma myortvogo cheloveka', count=1),
 Row(year='Pizza King', count=1),
 Row(year='Plunderers, The', count=2),
 Row(year="Pluto's Heart Throb", count=1),
 Row(year='Profesionalac', count=1),
 Row(year='Psycho from Texas', count=1),
 Row(year='Querelle', count=1),
 Row(year='Quo Vadis?', count=2),
 Row(year='Ragazze di piazza di Spagna, Le', count=1),
 Row(year='Rasputin: The Mad Monk', count=1),
 Row(year='Resist!: To Be with the Living', count=1),
 Row(year='Romeo-Juliet', count=1),
 Row(year='San Antone', count=1),
 Row(year='Saraband for Dead Lovers', count=1),
 Row(year='Scimitarra del Saraceno, La', count=1),
 Row(year='Screwball Football', count=1),
 Row(year='Sebastian and the Sparrow', count=1),
 Row(year='Secondo tragico Fantozzi, Il', count=1),
 Row(year='Secret Life of an American Wife, The', count=1),
 Row(year='See Jane Run', count=1),
 Row(year='Seins de glace, Les', count=1),
 Row(year='Senke uspomena', count=1),
 Row(year='Seven Servants', count=1),
 Row(year='Sex Under Glass', count=1),
 Row(year='Silk', count=1),
 Row(year='Smukke-Arne og Rosa', count=1),
 Row(year="Snowman's Land", count=1),
 Row(year='Sorcellerie culinaire', count=1),
 Row(year='Spanish Main, The', count=1),
 Row(year='Spinning Gasing', count=1),
 Row(year='Spirits of the Air, Gremlins of the Clouds', count=1),
 Row(year='Stand der Dinge, Der', count=1),
 Row(year='Stardom', count=1),
 Row(year='Stars in My Crown', count=1),
 Row(year='Steinflug', count=1),
 Row(year='Store, The', count=1),
 Row(year='Straight to Hell', count=1),
 Row(year='Stranger at My Door', count=1),
 Row(year='Street-Fighter', count=1),
 Row(year='Strelets neprikayannyy', count=1),
 Row(year='Stuff That Bear!', count=1),
 Row(year='Subida al cielo', count=1),
 Row(year='Sudden Manhattan', count=1),
 Row(year='Sugar & Spice', count=1),
 Row(year='Sunday Afternoon', count=1),
 Row(year='Superfly', count=1),
 Row(year='Surprise!', count=1),
 Row(year='Susanna', count=1),
 Row(year='Svadba', count=2),
 Row(year='Sweet Kill', count=1),
 Row(year='Tarzan, the Ape Man', count=2),
 Row(year='Terceira Margem do Rio, A', count=1),
 Row(year='Terror from the Year 5000', count=1),
 Row(year='Texasville', count=1),
 Row(year='That Strange Person', count=1),
 Row(year="There's a Girl in My Soup", count=1),
 Row(year='Thomas Crown Affair, The', count=2),
 Row(year='Three Loan Wolves', count=1),
 Row(year='Todesstrahlen des Dr. Mabuse, Die', count=1),
 Row(year='Tokimeki ni shisu', count=1),
 Row(year='Top Speed', count=1),
 Row(year='Traje, El', count=1),
 Row(year='Tumbas, Las', count=1),
 Row(year='Tystnaden', count=1),
 Row(year="Ultimo capodanno, L'", count=1),
 Row(year='Un zoo la nuit', count=1),
 Row(year='Und keiner weint mir nach', count=1),
 Row(year='Under Texas Skies', count=1),
 Row(year="Une histoire d'eau", count=1),
 Row(year='Une minute de silence', count=1),
 Row(year='Utah', count=1),
 Row(year='V poiskakh zolotogo fallosa', count=1),
 Row(year='Vakvagany', count=1),
 Row(year='Vento, di sera, Il', count=1),
 Row(year='Village Smithy, The', count=2),
 Row(year='Vizi morbosi di una governante, I', count=1),
 Row(year='Warm Corner, A', count=1),
 Row(year='Wild Man Blues', count=1),
 Row(year='Yue guang shao nian', count=1),
 Row(year='Zero Zero', count=1),
 Row(year="It's a Gift", count=2),
 Row(year='Naufragio', count=1),
 Row(year='Naustet', count=1),
 Row(year='Nemesis', count=1),
 Row(year='Riot in Rhythm', count=1),
 Row(year='Rufus Jones for President', count=1),
 Row(year='Sandy Hook Lingerie Party Massacre', count=1),
 Row(year='Second Chorus', count=1),
 Row(year="Size 'Em Up", count=1),
 Row(year='Studie Nr. 5', count=1),
 Row(year='Sunday Dinner for a Soldier', count=1),
 Row(year='Thunder Mountain', count=1),
 Row(year="We Can't Go Home Again", count=1),
 Row(year='Wild About Hurry', count=1),
 Row(year='Woman They Almost Lynched', count=1),
 Row(year='Zaza', count=2),
 Row(year='$windle', count=1),
 Row(year='1999 - Nen no natsu yasumi', count=1),
 Row(year='24-Seven', count=1),
 Row(year='3 dev adam', count=1),
 Row(year='Amerika', count=2),
 Row(year='Amori di Ercole, Gli', count=1),
 Row(year='Anam', count=1),
 Row(year='Anthropos gia oles tis douleies, O', count=1),
 Row(year='Appointment, The', count=3),
 Row(year="Archer's Adventure", count=1),
 Row(year='Arrebato', count=1),
 Row(year='Aruanda', count=1),
 Row(year='Atama-yama', count=1),
 Row(year='Atomik Circus - Le retour de James Bataille', count=1),
 Row(year='Babyface', count=1),
 Row(year='Barton Fink', count=1),
 Row(year='Beaches', count=1),
 Row(year='Bear Facts', count=1),
 Row(year='Bio-Tech Warrior', count=1),
 Row(year='Bitch', count=1),
 Row(year='Black Dawn', count=1),
 Row(year='Black Gold', count=2),
 Row(year='Black Spurs', count=1),
 Row(year='Blankman', count=1),
 Row(year='Blondie Hits the Jackpot', count=1),
 Row(year="Blondie's Secret", count=1),
 Row(year='Bockerer 2, Der', count=1),
 Row(year='Boulet, Le', count=1),
 Row(year='Breed Apart, A', count=1),
 Row(year='Britannia of Billingsgate', count=1),
 Row(year='Broken Leghorn, A', count=1),
 Row(year="C'era una volta il West", count=1),
 Row(year='Carte postale, La', count=1),
 Row(year='Charleston', count=1),
 Row(year='Chikyu Boeigun', count=1),
 Row(year='Chin gei bin', count=1),
 Row(year='China Shop, The', count=1),
 Row(year='City of the Dead, The', count=1),
 Row(year='Continental Twist, The', count=1),
 Row(year='Convicts', count=1),
 Row(year='CooCoo Nut Grove, The', count=1),
 Row(year='Copie conforme', count=1),
 Row(year='Cosas que hacen que la vida valga la pena', count=1),
 Row(year='Country Life', count=1),
 Row(year='Cowgirl', count=1),
 Row(year='Cracker Man, The', count=1),
 Row(year='Curtain Pole, The', count=1),
 Row(year='Da no tien gu', count=1),
 Row(year='Dagboek van een oude dwaas', count=1),
 Row(year='Decodings', count=1),
 Row(year='Detention', count=1),
 Row(year="Devil's in Love, The", count=1),
 Row(year='Direktan prenos', count=1),
 Row(year="Dirty Harry's Way", count=1),
 Row(year='Don Quijote de la Mancha', count=1),
 Row(year='Ebolusyon ng isang pamilyang pilipino', count=1),
 Row(year='Ediths Tagebuch', count=1),
 Row(year='Emilie Muller', count=1),
 Row(year='Encino Man', count=1),
 Row(year='Escape From Hellhole', count=1),
 Row(year='Essene', count=1),
 Row(year='EvenHand', count=1),
 Row(year='Faits divers', count=1),
 Row(year='Far Horizons, The', count=1),
 Row(year='Femme de chambre du Titanic, La', count=1),
 Row(year='Feuerzeug, Das', count=1),
 Row(year='Fighting Devil Dogs, The', count=1),
 Row(year='Final Voyage', count=1),
 Row(year='Five Star Final', count=1),
 Row(year='Footsteps in the Dark', count=1),
 Row(year='Forever Midnight', count=1),
 Row(year='Freccia azzurra, La', count=1),
 Row(year='French Connection II', count=1),
 Row(year='Geh, zieh dein Dirndl aus', count=1),
 Row(year='Getting of Wisdom, The', count=1),
 Row(year="Goin' Down the Road", count=1),
 Row(year='Gottlieb', count=1),
 Row(year='Graffiante desiderio', count=1),
 Row(year='Greed', count=1),
 Row(year='Greedy for Tweety', count=1),
 Row(year='Guarding Eddy', count=1),
 Row(year='Hail Columbia', count=1),
 Row(year='Hard Hombre', count=1),
 Row(year='Harold & Kumar Go to White Castle', count=1),
 Row(year='Hawaii', count=1),
 Row(year='Heatscore', count=1),
 Row(year='Hidden, The', count=2),
 Row(year='Hitler--Dead or Alive', count=1),
 Row(year='Holiday Greetings 1941', count=1),
 Row(year='Home in Oklahoma', count=1),
 Row(year='Homo Videocus', count=1),
 Row(year='Hostile Environment', count=1),
 Row(year='How to Make Friends', count=1),
 Row(year='Huling birhen sa lupa, Ang', count=1),
 Row(year='Im Juli.', count=1),
 Row(year='Immoral Mr. Teas, The', count=1),
 Row(year='In Love', count=1),
 Row(year='In Oranje', count=1),
 Row(year='In This Our Life', count=1),
 Row(year='In the Pink', count=1),
 Row(year='In viaggio con Che Guevara', count=1),
 Row(year='Indien', count=2),
 Row(year='Inkwell, The', count=1),
 Row(year='Interesting Story, An', count=1),
 Row(year='Invisible Menace, The', count=1),
 Row(year='Jakten', count=1),
 Row(year='Jazzgossen', count=1),
 Row(year='Joe Louis Story, The', count=1),
 Row(year="Joe's Bed-Stuy Barbershop: We Cut Heads", count=1),
 Row(year='Jungle Fever', count=1),
 Row(year='Kalaa, El', count=1),
 Row(year='Ki lo sa?', count=1),
 Row(year='Kisses and Caroms', count=1),
 Row(year="Lady Windermere's Fan", count=1),
 Row(year='Laina-aika', count=1),
 Row(year="Lassie's Great Adventure", count=1),
 Row(year='Last of the Mohicans, The', count=3),
 Row(year='Lef', count=1),
 Row(year='Little Big League', count=1),
 Row(year='Loaded Weapon 1', count=1),
 Row(year='Lone Wolf Spy Hunt, The', count=1),
 Row(year='Long Dark Hall, The', count=1),
 Row(year='Lover Girl', count=1),
 Row(year='Lucky Ducky', count=1),
 Row(year='Mad Dog and Glory', count=1),
 Row(year='Magic Carpet, The', count=1),
 Row(year='Malizia erotica', count=1),
 Row(year='Man Who Came Back, The', count=1),
 Row(year='Man from Beyond, The', count=1),
 Row(year="Marche de l'empereur, La", count=1),
 Row(year='Mare nostrum', count=1),
 Row(year='Married/Unmarried', count=1),
 Row(year='Me and Will', count=1),
 Row(year='Menino e o Vento, O', count=1),
 Row(year='Messia, Il', count=1),
 Row(year='Milano trema - la polizia vuole giustizia', count=1),
 Row(year='Miserables, Les', count=1),
 Row(year='Mission to Mars', count=1),
 Row(year='Mistertao', count=1),
 Row(year='Mr. Emmanuel', count=1),
 Row(year='Mr. Freedom', count=1),
 Row(year='Must Be the Music', count=1),
 Row(year='Natural Born Gambler, A', count=1),
 Row(year='Night God Screamed, The', count=1),
 Row(year='Night of Horror', count=1),
 Row(year='Nude on the Moon', count=1),
 Row(year='Of Fox and Hounds', count=1),
 Row(year='Okay', count=1),
 Row(year='Oktyabr', count=1),
 Row(year='One Perfect Day', count=1),
 Row(year='Pahat pojat', count=1),
 Row(year='Paloma de papel', count=1),
 Row(year='Parnell', count=1),
 Row(year='Pasolini, un delitto italiano', count=1),
 Row(year='Patrizia', count=1),
 Row(year='Petite apocalypse, La', count=1),
 Row(year='Piratene', count=1),
 Row(year='Plastics Inventor, The', count=1),
 Row(year="Poet's Pub", count=1),
 Row(year='Portrait of a Mobster', count=1),
 Row(year='Prokhindiada, ili beg na meste', count=1),
 Row(year='Proshu slova', count=1),
 Row(year='Q Planes', count=1),
 Row(year='Quadrophenia', count=1),
 Row(year='Raging Moon, The', count=1),
 Row(year='Rattenskat', count=1),
 Row(year='Return Engagement', count=1),
 Row(year='Road to God Knows Where, The', count=1),
 Row(year='Road to Morocco', count=1),
 Row(year='Romeo e Giulietta', count=1),
 Row(year='Rooty Toot Toot', count=1),
 Row(year='Salla, La', count=1),
 Row(year='Schauspielerin, Die', count=1),
 Row(year='Sexplorer', count=1),
 Row(year='Shape Ahoy', count=1),
 Row(year='Shiraz', count=1),
 Row(year='Shopping Part, The', count=1),
 Row(year='Sin noticias de Dios', count=1),
 Row(year="Smart Girls Don't Talk", count=1),
 Row(year='Smic Smac Smoc', count=1),
 Row(year='Smiling Lieutenant, The', count=1),
 Row(year='Sobrenatural', count=1),
 Row(year='Sonora Stagecoach', count=1),
 Row(year='Souper, Le', count=1),
 Row(year='Space-Thing', count=1),
 Row(year='Squirm', count=1),
 Row(year='St. Ives', count=2),
 Row(year='Star Dust', count=1),
 Row(year='Stjerner uden hjerner', count=1),
 Row(year='Super rapina a Milano', count=1),
 Row(year='Swiss Miss', count=1),
 Row(year='Taeyangeun eobda', count=1),
 Row(year='Tale of Two Sisters, A', count=1),
 Row(year='Tamahine', count=1),
 Row(year='Testament of Tom Jacoby, The', count=1),
 Row(year='Things You Can Tell Just by Looking at Her', count=1),
 Row(year='Thisavros tou makariti, O', count=1),
 Row(year='Three for Bedroom C', count=1),
 Row(year='Tic Code, The', count=1),
 Row(year='Timecop: The Berlin Decision', count=1),
 Row(year='Tirez sur le pianiste', count=1),
 Row(year='Tis a Gift to Be Simple', count=1),
 Row(year='Tom and Jerry Cartoon Kit, The', count=1),
 Row(year='Trade Off', count=1),
 Row(year='Tre giorni di anarchia', count=1),
 Row(year='Treci kljuc', count=1),
 Row(year='Tres tristes tigres', count=1),
 Row(year='Trouble Every Day', count=1),
 Row(year='Tsuma wa kokuhaku suru', count=1),
 Row(year='Tumba de los muertos vivientes, La', count=1),
 Row(year='Une femme douce', count=1),
 Row(year='Une place parmi les vivants', count=1),
 Row(year='Uprowadzenie Agaty', count=1),
 Row(year='Versace Murder, The', count=1),
 Row(year='Vida es silbar, La', count=1),
 Row(year='Where Love Has Gone', count=1),
 Row(year='Window Water Baby Moving', count=1),
 Row(year='Workshop Junkie, The', count=1),
 Row(year="Young Don't Cry, The", count=1),
 Row(year='Land Unknown, The', count=1),
 Row(year='Lion volatile, Le', count=1),
 Row(year='Lola Zipper', count=1),
 Row(year='Lost Weekend', count=1),

In [23]:
df.year

Column<b'year'>

In [24]:
df.collect()[0].get(0)

AttributeError: get

In [25]:
rdd_data = df.rdd

In [26]:
df.toPandas()

,Action,Animation,Comedy,Documentary,Drama,Romance,budget,length,mpaa,r1,...,r3,r4,r5,r6,r7,r8,r9,rating,votes,year
0,nan,0,0,1,1,0,121,1971,4.5,348,...,4.5,4.5,4.5,14.5,24.5,24.5,14.5,nan,6.4,$
1,nan,0,0,0,1,0,71,1939,14.5,20,...,14.5,4.5,24.5,14.5,14.5,14.5,4.5,nan,6.0,$1000 a Touchdown
2,nan,0,1,0,0,0,7,1941,24.5,5,...,0.0,0.0,0.0,0.0,24.5,0.0,44.5,nan,8.2,$21 a Day Once a Month
3,nan,0,0,0,1,0,70,1996,45.5,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,8.2,"$40,000"
4,nan,0,0,0,0,0,71,1975,24.5,17,...,4.5,0.0,14.5,14.5,4.5,0.0,0.0,nan,3.4,"$50,000 Climax Show, The"
5,nan,0,0,1,0,0,91,2000,14.5,45,...,4.5,4.5,14.5,14.5,14.5,4.5,4.5,nan,4.3,$pent
6,R,1,0,1,0,0,93,2002,14.5,200,...,0.0,4.5,4.5,24.5,24.5,14.5,4.5,nan,5.3,$windle
7,nan,0,0,0,0,1,25,2002,14.5,24,...,4.5,4.5,4.5,4.5,14.5,14.5,14.5,nan,6.7,'15'
8,nan,0,0,1,0,0,97,1987,24.5,18,...,4.5,4.5,0.0,0.0,0.0,34.5,14.5,nan,6.6,'38
9,nan,0,0,0,0,0,61,1917,4.5,51,...,0.0,4.5,4.5,4.5,44.5,14.5,4.5,nan,6.0,'49-'17
10,nan,0,0,1,0,0,99,1988,4.5,23,...,0.0,4.5,14.5,24.5,4.5,24.5,4.5,nan,5.4,'68
11,nan,0,0,0,0,0,96,1994,24.5,53,...,0.0,4.5,4.5,4.5,14.5,24.5,14.5,nan,5.9,'94 du bi dao zhi qing
12,nan,0,0,0,1,0,10,1906,14.5,44,...,0.0,0.0,0.0,4.5,14.5,34.5,14.5,nan,7.0,"'?' Motorist, The"
13,nan,0,0,0,0,0,10,1965,24.5,11,...,0.0,0.0,0.0,0.0,14.5,4.5,4.5,nan,6.7,'A'
14,PG-13,1,0,0,1,0,106,1983,24.5,1259,...,4.5,4.5,4.5,4.5,14.5,14.5,14.5,nan,7.1,'A' gai waak
15,PG-13,1,0,0,1,0,101,1987,14.5,614,...,4.5,4.5,4.5,4.5,14.5,24.5,24.5,nan,7.2,'A' gai waak juk jaap
16,nan,0,0,1,0,0,107,1980,24.5,2718,...,4.5,4.5,4.5,4.5,4.5,14.5,24.5,nan,7.9,'Breaker' Morant
17,nan,0,0,0,0,1,10,1968,4.5,37,...,0.0,4.5,4.5,4.5,14.5,44.5,14.5,nan,6.6,'Bullitt': Steve McQueen's Commitment to Reality
18,nan,1,0,0,1,0,110,1988,4.5,7252,...,4.5,4.5,14.5,24.5,24.5,14.5,4.5,nan,5.0,'Crocodile' Dundee II
19,nan,0,1,0,1,0,7,1981,45.5,15,...,0.0,0.0,0.0,4.5,4.5,0.0,14.5,nan,8.6,'E'
20,nan,0,0,0,1,0,90,1995,24.5,10,...,14.5,24.5,14.5,0.0,14.5,14.5,0.0,nan,3.9,'El Chicko' - der Verdacht
21,nan,0,0,1,0,0,85,1935,4.5,281,...,4.5,4.5,4.5,4.5,14.5,34.5,34.5,450000.0,7.2,'G' Men
22,nan,1,0,1,0,0,88,1974,4.5,100,...,14.5,24.5,14.5,14.5,4.5,4.5,4.5,nan,3.5,'Gator Bait
23,nan,0,0,0,0,0,95,1988,4.5,54,...,14.5,4.5,14.5,4.5,14.5,0.0,4.5,nan,3.1,'Gator Bait II: Cajun Justice
24,nan,0,0,0,1,0,18,1921,14.5,145,...,0.0,4.5,0.0,4.5,14.5,24.5,24.5,nan,7.8,"'High Sign', The"
25,nan,0,0,0,0,0,80,1979,34.5,45,...,0.0,4.5,4.5,4.5,4.5,24.5,14.5,nan,7.7,'Hukkunud Alpinisti' hotell
26,nan,0,1,0,1,0,6,1935,0.0,18,...,0.0,0.0,24.5,0.0,24.5,14.5,14.5,nan,6.2,"'Hyp-Nut-Tist', The"
27,nan,0,0,0,0,0,86,1989,14.5,10,...,0.0,0.0,24.5,24.5,14.5,24.5,14.5,nan,6.2,'I Do...'
28,nan,0,0,1,0,0,92,1945,34.5,825,...,4.5,4.5,4.5,4.5,4.5,14.5,14.5,nan,7.7,'I Know Where I'm Going!'
29,nan,0,0,0,1,0,7,1995,34.5,10,...,14.5,0.0,0.0,14.5,14.5,34.5,0.0,nan,6.8,'Java Madness' formerly titled 'Coffee Madness'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58758,nan,0,0,0,0,0,95,1982,4.5,13,...,0.0,0.0,0.0,0.0,34.5,24.5,4.5,nan,6.4,"Zwoele zomeravond, Een"
58759,nan,0,0,0,0,0,90,1992,24.5,9,...,0.0,0.0,0.0,14.5,0.0,44.5,24.5,nan,6.9,Zwolnieni z zycia
58760,nan,0,0,1,0,0,99,2000,14.5,97,...,0.0,0.0,4.5,4.5,4.5,34.5,24.5,nan,7.0,Zycie jako smiertelna choroba przenoszona drog...
58761,nan,0,0,1,0,0,88,1971,4.5,14,...,4.5,0.0,0.0,24.5,14.5,4.5,4.5,nan,6.0,Zycie rodzinne
58762,nan,0,0,0,0,0,86,1987,24.5,8,...,0.0,0.0,0.0,0.0,24.5,0.0,34.5,nan,6.5,Zycie wewnetrzne
58763,nan,0,0,0,0,0,90,1991,34.5,10,...,0.0,14.5,14.5,24.5,0.0,0.0,24.5,nan,5.1,Zycie za zycie
58764,nan,0,0,1,0,0,46,1975,44.5,5,...,0.0,0.0,24.5,0.0,0.0,24.5,0.0,nan,3.6,Zyciorys
58765,nan,0,0,1,0,0,86,1999,24.5,5,...,0.0,44.5,0.0,0.0,0.0,44.5,0.0,nan,6.0,Zyklus von Kleinigkeiten
58766,R,0,0,0,0,0,75,1995,0.0,19,...,4.5,14.5,14.5,14.5,14.5,14.5,4.5,nan,3.7,Zyosyuu syukeininn Maria
58767,nan,0,0,1,0,0,80,1967,34.5,31,...,4.5,4.5,4.5,4.5,0.0,4.5,14.5,nan,5.4,Zywot Mateusza
58768,nan,0,0,0,0,0,94,2000,4.5,45,...,4.5,4.5,24.5,24.5,14.5,4.5,4.5,nan,4.7,Zzikhimyeon jukneunda
58769,nan,0,0,0,0,0,101,1998,0.0,14,...,4.5,24.5,4.5,14.5,24.5,0.0,4.5,nan,4.5,Zzim
58770,nan,0,0,0,0,0,90,2005,64.5,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1000000.0,8.0,Zzyzx
58771,nan,0,0,1,0,0,89,2000,4.5,186,...,4.5,4.5,4.5,4.5,14.5,14.5,24.5,nan,6.2,alaska.de
58772,nan,0,1,0,0,0,3,1987,0.0,6,...,0.0,0.0,14.5,45.5,0.0,34.5,0.0,nan,5.7,barefootin'
58773,nan,0,0,1,0,0,120,2002,4.5,53,...,4.5,0.0,4.5,4.5,0.0,4.5,4.5,nan,6.9,deadend.com
58774,nan,0,0,0,0,1,94,2001,14.5,86,...,0.0,0.0,4.5,4.5,14.5,14.5,34.5,nan,6.8,e-Dreams
58775,nan,0,0,0,1,0,17,2001,24.5,15,...,0.0,0.0,4.5,4.5,4.5,0.0,24.5,nan,7.3,eMale
58776,nan,0,0,0,1,0,9,2003,44.5,5,...,0.0,0.0,0.0,0.0,44.5,0.0,0.0,nan,6.0,eRATicate
58777,nan,0,0,1,0,0,78,2002,24.5,11,...,0.0,0.0,0.0,0.0,4.5,0.0,14.5,nan,4.2,eXXXorcismos
58778,R,0,0,1,0,0,97,1999,4.5,14742,...,4.5,4.5,4.5,4.5,14.5,24.5,24.5,nan,6.7,eXistenZ
58779,nan,0,0,0,0,0,20,2002,24.5,13,...,0.0,4.5,4.5,14.5,0.0,14.5,4.5,nan,5.0,f2point8
58780,nan,0,1,0,0,0,13,2001,0.0,7,...,0.0,0.0,0.0,0.0,24.5,14.5,24.5,nan,7.6,f8
58781,nan,0,0,0,0,0,87,1998,14.5,6,...,14.5,14.5,14.5,0.0,34.5,0.0,0.0,nan,5.2,pURe kILLjoy
58782,nan,1,0,0,0,0,15,2002,24.5,8,...,0.0,0.0,14.5,0.0,0.0,24.5,14.5,nan,7.0,sIDney
58783,nan,0,1,0,0,0,98,1958,4.5,274,...,4.5,4.5,4.5,14.5,14.5,24.5,14.5,nan,6.5,tom thumb
58784,nan,0,0,1,0,0,105,2003,24.5,12,...,0.0,0.0,0.0,0.0,0.0,24.5,0.0,nan,1.1,www.XXX.com
58785,nan,0,0,0,0,0,100,1999,44.5,5,...,0.0,24.5,0.0,0.0,0.0,0.0,0.0,nan,6.6,www.hellssoapopera.com
58786,PG-13,1,0,0,0,0,132,2002,4.5,18514,...,4.5,4.5,4.5,14.5,14.5,14.5,14.5,85000000.0,5.5,xXx
58787,PG-13,1,0,0,0,0,101,2005,14.5,1584,...,4.5,4.5,4.5,4.5,14.5,4.5,4.5,87000000.0,3.9,xXx: State of the Union

In [27]:
sc.stop()